### ISSUE TITLE
certificate of host for dailymotion sample .zip is invalid (for host)

### ISSUE THREAD

**Issue by wonderfly** [google/google-oauth-java-client#97] opened 2015-01-09 21:51 UTC
_From [jeff.gr...@gmail.com](https://code.google.com/u/102273149213838524704/) on July 21, 2014 15:13:15_

Version of google-oauth-java-client (e.g. 1.5.0-beta)? current code.google.com project pages.  The link (specified below) is on the source page for the DailyMotion.java sample. Describe the problem. This page https://samples.google-oauth-java-client.googlecode.com/archive/b6eab40731f176c1162f1b391642c2590eb1f61e.zip cannot be loaded by Chrome because the server certificate (CN=*.googlecode.com) is not valid for the server.  (The wildcard only applies one level deep in the domain hierarchy, I think.) How would you expect it to be fixed? Install correct certificate on this host.

Workaround:  Download with, e.g., curl, specifying that the certificate be accepted regardless.

_Original issue: http://code.google.com/p/google-oauth-java-client/issues/detail?id=97_

**Comment by mattwhisenhunt** [comment] 2018-03-16 17:09
Duplicate of #132

**Closed by mattwhisenhunt** 2018-03-16 17:09 UTC
Labels: 2–5 stars, imported, type: bug
